---
title: "UVA Basketball"
output: html_document
date: "2023-02-09"
---

```{r}
library(dplyr)
library(rvest)
library(tidyverse)
library(stringr)
```

```{r}
website = "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-virginia-tech-hokies-feb-04-2023-game-boxscore-242255?tab=playbyplay"
fox = read_html(website)
```

```{r}
first_half<-fox%>%
  html_nodes(".flex-col:nth-child(1)")%>%
  html_text()
second_half<-fox%>%
  html_nodes(".final+ .final")%>%
  html_text()
```

```{r}
fh_plays<-data.frame(first_half)
head(fh_plays,10)
fh_plays = toString(fh_plays)
print(fh_plays)
sh_plays<-data.frame(second_half)
head(sh_plays,10)
sh_plays = toString(sh_plays)
print(sh_plays)
```

```{r}
fh_array = strsplit(fh_plays,split = '\n   ')
sh_array = strsplit(sh_plays,split = '\n   ')
```

```{r}
fh_table = as.data.frame(matrix(unlist(fh_array),ncol=2,byrow=T))
sh_table = as.data.frame(matrix(unlist(sh_array),ncol=2,byrow=T))
```

```{r}
vt_game = rbind(fh_table,sh_table)
vt_game = na.omit(vt_game)
```

```{r}
vt_game = vt_game %>% rename(Time = V1, Description = V2)
```

```{r}
vt_game$Event = ""
```


```{r}

vt_game[grepl("makes three", vt_game$Description, fixed = TRUE),]$Event = "Made Three"
vt_game[grepl("makes two", vt_game$Description, fixed = TRUE),]$Event = "Made Two"
vt_game[grepl("makes", vt_game$Description, fixed = TRUE) & grepl("free throw", 
                                                                  vt_game$Description, fixed = TRUE),]$Event = "Made FT"

vt_game[grepl("misses three", vt_game$Description, fixed = TRUE),]$Event = "Missed Three"
vt_game[grepl("misses two", vt_game$Description, fixed = TRUE),]$Event = "Missed Two"
vt_game[grepl("misses", vt_game$Description, fixed = TRUE) &
          grepl("free throw", vt_game$Description, fixed = TRUE),]$Event = "Missed FT"
vt_game[grepl("turnover", vt_game$Description, fixed = TRUE),]$Event = "Turnover"
vt_game[grepl("block", vt_game$Description, fixed = TRUE),]$Event = "Block"
vt_game[grepl("offensive rebound", vt_game$Description, fixed = TRUE),]$Event = "Off Rebound"
vt_game[grepl("defensive rebound", vt_game$Description, fixed = TRUE),]$Event = "Def Rebound"
vt_game[grepl("second timeout", vt_game$Description, fixed = TRUE),]$Event = "Timeout"
vt_game[grepl("Jump ball", vt_game$Description, fixed = TRUE),]$Event = "Jump Ball"


vt_game[grepl("lineup", vt_game$Description, fixed = TRUE),]$Event = "Opp Sub"
vt_game[grepl("Cavaliers lineup", vt_game$Description, fixed = TRUE),]$Event = "Cav Sub"

vt_game[grepl("shooting foul", vt_game$Description, fixed = TRUE) | 
          grepl("personal foul", vt_game$Description, fixed = TRUE),]$Event = "Foul"

```


## Refer to R file for rest of code ##

```{r}
library("rvest")
library("ggplot2")
library("tidyverse")
library("useful")

### Reading in Website

websites = c("https://www.foxsports.com/college-basketball/north-carolina-central-eagles-vs-virginia-cavaliers-nov-07-2022-game-boxscore-239938?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/monmouth-hawks-vs-virginia-cavaliers-nov-11-2022-game-boxscore-239939?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/continental-tire-main-event-baylor-bears-vs-virginia-cavaliers-nov-18-2022-game-boxscore-239941?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/continental-tire-main-event-virginia-cavaliers-vs-illinois-fighting-illini-nov-20-2022-game-boxscore-244972?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/maryland-eastern-shore-hawks-vs-virginia-cavaliers-nov-25-2022-game-boxscore-239942?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-michigan-wolverines-nov-29-2022-game-boxscore-240892?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/florida-state-seminoles-vs-virginia-cavaliers-dec-03-2022-game-boxscore-239943?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/james-madison-dukes-vs-virginia-cavaliers-dec-06-2022-game-boxscore-239944?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/houston-cougars-vs-virginia-cavaliers-dec-17-2022-game-boxscore-239945?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-miami-fl-hurricanes-dec-20-2022-game-boxscore-242282?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/albany-great-danes-vs-virginia-cavaliers-dec-28-2022-game-boxscore-239946?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-georgia-tech-yellow-jackets-dec-31-2022-game-boxscore-242427?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-pittsburgh-panthers-jan-03-2023-game-boxscore-240102?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/syracuse-orange-vs-virginia-cavaliers-jan-07-2023-game-boxscore-239947?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/north-carolina-tar-heels-vs-virginia-cavaliers-jan-10-2023-game-boxscore-239948?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-florida-state-seminoles-jan-14-2023-game-boxscore-241060?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-tech-hokies-vs-virginia-cavaliers-jan-18-2023-game-boxscore-239949?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-wake-forest-demon-deacons-jan-21-2023-game-boxscore-242875?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/boston-college-eagles-vs-virginia-cavaliers-jan-28-2023-game-boxscore-239950?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-syracuse-orange-jan-30-2023-game-boxscore-239641?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-virginia-tech-hokies-feb-04-2023-game-boxscore-242255?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/north-carolina-state-wolfpack-vs-virginia-cavaliers-feb-07-2023-game-boxscore-239951?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/duke-blue-devils-vs-virginia-cavaliers-feb-11-2023-game-boxscore-239952?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-louisville-cardinals-feb-15-2023-game-boxscore-241968?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/notre-dame-fighting-irish-vs-virginia-cavaliers-feb-18-2023-game-boxscore-239953?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-boston-college-eagles-feb-22-2023-game-boxscore-239995?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/virginia-cavaliers-vs-north-carolina-tar-heels-feb-25-2023-game-boxscore-243540?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/clemson-tigers-vs-virginia-cavaliers-feb-28-2023-game-boxscore-239954?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/louisville-cardinals-vs-virginia-cavaliers-mar-04-2023-game-boxscore-239955?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/conference-tournament-north-carolina-tar-heels-vs-virginia-cavaliers-mar-09-2023-game-boxscore-245316?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/conference-tournament-clemson-tigers-vs-virginia-cavaliers-mar-10-2023-game-boxscore-245319?tab=playbyplay",
             "https://www.foxsports.com/college-basketball/conference-tournament-duke-blue-devils-vs-virginia-cavaliers-mar-11-2023-game-boxscore-245320?tab=playbyplay")
starting_lineups = c("Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Jayden Gardner,Kihei Clark,Isaac McKneely,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Kadin Shedrick,Reece Beekman,Jayden Gardner",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Ben Vander Plas",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Francisco Caffaro",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Francisco Caffaro",
                     "Armaan Franklin,Kihei Clark,Reece Beekman,Jayden Gardner,Francisco Caffaro")
abbrevs = c("NCCU",
            "MONM",
            "BAY",
            "ILL",
            "UMES",
            "MICH",
            "FSU",
            "JMU",
            "HOU",
            "MIA",
            "ALBY",
            "GT",
            "PITT",
            "SYR",
            "UNC",
            "FSU",
            "VT",
            "WAKE",
            "BC",
            "SYR",
            "VT",
            "NCST",
            "DUKE",
            "LOU",
            "ND",
            "BC",
            "UNC",
            "CLEM",
            "LOU",
            "UNC",
            "CLEM",
            "DUKE")
games = tibble(Time = "", Description = "", Event = "", Token = "", words = strsplit("place holder", split = ' '), Player = "", 
               UVA_score = 0, Opp_score = 0, Time_in_sec = 0)

```

```{r}
fox = read_html(websites[3])

first_half<-fox%>%
  html_nodes(".flex-col:nth-child(1)")%>%
  html_text()
second_half<-fox%>%
  html_nodes(".final+ .final")%>%
  html_text()

fh_plays<-data.frame(first_half)
head(fh_plays,10)
fh_plays = toString(fh_plays)
sh_plays<-data.frame(second_half)
head(sh_plays,10)
sh_plays = toString(sh_plays)

fh_array = strsplit(fh_plays,split = '\n   ')
sh_array = strsplit(sh_plays,split = '\n   ')

fh_table = as.data.frame(matrix(unlist(fh_array),ncol=2,byrow=T))
sh_table = as.data.frame(matrix(unlist(sh_array),ncol=2,byrow=T))

game = rbind(fh_table,sh_table)
game = na.omit(game)

### Cleaning Dataset
colnames(game) = c("Time1", "Description")
game$Description = substr(game$Description, 4, 125)

starters = paste("Cavaliers lineup change (", starting_lineups[3], sep = '')
game = add_row(game, Time1 = "20:00", Description = paste(starters, ")", sep = ''),.before = 1)
game = add_column(game, Time = str_remove_all(game$Time1, " "), .before = "Time1")

## Creating an Event Column
game$Event = ""

game[grepl("makes three", game$Description, fixed = TRUE),]$Event = "Made Three"
game[grepl("makes two", game$Description, fixed = TRUE),]$Event = "Made Two"
game[grepl("makes", game$Description, fixed = TRUE) & grepl("free throw", 
                                                                  game$Description, fixed = TRUE),]$Event = "Made FT"

game[grepl("misses three", game$Description, fixed = TRUE),]$Event = "Missed Three"
game[grepl("misses two", game$Description, fixed = TRUE),]$Event = "Missed Two"
game[grepl("misses", game$Description, fixed = TRUE) &
          grepl("free throw", game$Description, fixed = TRUE),]$Event = "Missed FT"
game[grepl("turnover", game$Description, fixed = TRUE),]$Event = "Turnover"
game[grepl("block", game$Description, fixed = TRUE),]$Event = "Block"
game[grepl("offensive rebound", game$Description, fixed = TRUE),]$Event = "Off Rebound"
game[grepl("defensive rebound", game$Description, fixed = TRUE),]$Event = "Def Rebound"
game[grepl("second timeout", game$Description, fixed = TRUE),]$Event = "Timeout"

```

```{r}
if (length(game[grepl("Jump ball", game$Description, fixed = TRUE)]) >0){
 game[grepl("Jump ball", game$Description, fixed = TRUE),]$Event = "Jump Ball" 
}


game[grepl("lineup", game$Description, fixed = TRUE),]$Event = "Opp Sub"
game[grepl("Cavaliers lineup", game$Description, fixed = TRUE),]$Event = "Cav Sub"

game[grepl("shooting foul", game$Description, fixed = TRUE) | 
          grepl("personal foul", game$Description, fixed = TRUE),]$Event = "Foul"


#game[grepl("flagrant", game$Description, fixed = TRUE),]$Event = "Flagrant"

## Creating a Player Column

# Create a token to split the strings on
game$Token = " "

game[grepl("makes", game$Description, fixed = TRUE),]$Token = "makes"
game[grepl("misses", game$Description, fixed = TRUE),]$Token = "misses"
game[grepl("turnover", game$Description, fixed = TRUE),]$Token = "turnover"
game[grepl("block", game$Description, fixed = TRUE),]$Token = "block"

game[grepl("offensive rebound", game$Description, fixed = TRUE),]$Token = "offensive rebound"
game[grepl("defensive rebound", game$Description, fixed = TRUE),]$Token = "defensive rebound"
game[grepl("second timeout", game$Description, fixed = TRUE),]$Token = "second timeout"

game[grepl("shooting foul", game$Description, fixed = TRUE),]$Token = "shooting foul"
game[grepl("personal foul", game$Description, fixed = TRUE),]$Token = "personal foul"

# split on the token, take the first element (player doing action)
game$words = strsplit(game$Description, game$Token)
game$Player = sapply(game$words,"[[",1) 
game$Player = substr(game$Player, 0, nchar(game$Player)-1)


UVA_roster = c("Kihei Clark", "Reece Beekman", "Armaan Franklin", "Jayden Gardner", 
               "Ben Vander Plas", "Kadin Shedrick", "Francisco Caffaro", "Ryan Dunn",
               "Isaac McKneely", "Taine Murray", "Chase Coleman", "Tristan How", "Cavaliers")


game$UVA_score = 0
game$Opp_score = 0

for( i in 2:nrow(game)) {
  
  scoreDif = 0
  oppScoreDif = 0
  
  if (game$Token[i] == "makes") {
    
    if(game$Player[i] %in% UVA_roster) {
      
      if(game$Event[i] == "Made FT") {
        scoreDif = 1
      } else if (game$Event[i] == "Made Two") {
        scoreDif = 2
      } else if (game$Event[i] == "Made Three") {
        scoreDif = 3
      }
      
      
    } else {
      
      if(game$Event[i] == "Made FT") {
        oppScoreDif = 1
      } else if (game$Event[i] == "Made Two") {
        oppScoreDif = 2
      } else if (game$Event[i] == "Made Three") {
        oppScoreDif = 3
      }
      
    }
    
  }
  game$UVA_score[i] = game$UVA_score[i-1] + scoreDif
  game$Opp_score[i] = game$Opp_score[i-1] + oppScoreDif
}

### Cleaning for Time and usable Time in seconds

game$Time_in_sec = 0 

for( i in 1:nrow(game)) {
  extra = c('1STHALF','2NDHALF',paste(abbrevs[3],as.character(game$Opp_score[i-1]), sep = ''), paste('UVA',as.character(game$UVA_score[i-1]), sep = ''))
  for (e in extra) {
    game$Time[i] = gsub(e,'',game$Time[i])
  }
  min_sec = as.character(game$Time[i])
  if (str_length(min_sec) == 4) {
    min_sec = paste('0',min_sec, sep = '')
  }
  game$Time_in_sec[i] = as.numeric(substr(min_sec, 1, 2))*60 + as.numeric(substr(min_sec, 4, 5))
}
game = game %>% select(-Time1)
game = na.omit(game)

games = rbind(games,game)

```







